spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/bobzip
    username: sa
    password:
    p6spy:
      enabled: true
      appender: com.p6spy.engine.spy.appender.Slf4JLogger
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true



# 이미지 파일 저장 경로
image.dir : C:/Users/ekore/file/
recipeThumbnail.dir : C:/Users/ekore/file/recipe/
stepThumbnail.dir : C:/Users/ekore/file/step/